name: kessoku
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - from-file: steam-packages.yml
  - from-file: hyprland-packages.yml
  - from-file: common-packages.yml
  - from-file: jp-packages.yml
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - FiraCode
  - type: files
    files:
      - usr: /usr 
  - type: script
    scripts:
      - remove_annoying_justfile_generator.sh
  - type: default-flatpaks # set up flathub
    system:
  - type: signing
