name: kessoku
description: This is my personal OS image.

# base-image: ghcr.io/ublue-os/base-main
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: latest

modules:
  - from-file: podman.yml
  # - from-file: steam-packages.yml
  # - from-file: hyprland-packages.yml
  # - from-file: river-packages.yml
  - from-file: common-packages.yml
  - from-file: jp-packages.yml
  - from-file: bazzite.yml
  # - from-file: cosmic-packages.yml
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - FiraCode
  - type: files
    files:
      - source: system
        destination: /
  - type: script
    scripts:
      - remove_annoying_justfile_generator.sh
  # - type: rpm-ostree
  #   remove:
  #     - firefox
  #     - firefox-langpacks
  # - type: default-flatpaks # set up flathub
  #   system:
  #     install:
  #       - org.mozilla.firefox
  - type: signing
